server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
