server:
  port: 8080

spring:
  application:
    name: food-delivery
  # datasource setting
  datasource:
    url: jdbc:postgresql://ep-flat-sky-a5t8vcwf.us-east-2.aws.neon.tech/test?user=test_owner&password=7qZRvuB4tLJl&sslmode=require
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  ##
  jpa:
    # Hibernate ddl auto (none, create, create-drop, validate, update)
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    database: postgresql
    properties:
      hibernate:
        format_sql: true
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # servlet setting
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ## redis setting
  data:
    redis:
      host:
      port:

#  flyway:
#    locations: classpath:/db/migration, classpath:/db/dev/migration
#    baseline-on-migrate: true
#    baseline-version: 0

application:
  jwt:
    secret-key: FDjhBadj3d6X3df9WYac+DhnK1dK4xqj567N1+HHRv4=
    expiration: 900000
    refresh-expiration: 604800000

logging:
  level:
    org.springframework.security: TRACE

