import '@styles/globals.css';
import { MainLayout } from '@/layouts';
import type { Metadata } from 'next';
import { ThemeProvider } from '@/provider';
import { PageTransition } from '@/components/molecule';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MainLayout>
            <PageTransition>{children}</PageTransition>
          </MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
