import "@styles/globals.css";
import { MainLayout } from "@/layouts";
import type { Metadata } from "next";
import Providers from "@/provider";
import { PageTransition } from "@/components/molecule";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-accent">
        <Providers>
          <MainLayout>
            <PageTransition>
              <div className="h-screen overflow-auto hide-scrollbar">
                {children}
              </div>
            </PageTransition>
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
