export const QUERIES_KEY = {
  AUTH: {
    SIGN_IN: "SIGN_IN_USER",
    SIGN_UP: "SIGN_UP_USER",
    SEND_OTP: "SEND_OTP",
    VERIFICATION_EMAIL: "VERIFICATION_EMAIL",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    PHONE_REGISTER: "PHONE_REGISTER",
    SOCIAL_CALLBACK: "SOCIAL_CALLBACK",
  },
};
